# Generated by Django 3.2.2 on 2021-05-23 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directoryapp', '0002_invitation_last_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='token',
        ),
    ]
