# Generated by Django 3.2.2 on 2021-05-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryapp', '0003_remove_invitation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='link',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
