# Generated by Django 3.2.2 on 2021-05-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryapp', '0008_remove_tenant_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='private_use',
            field=models.BooleanField(default=False),
        ),
    ]
