# Generated by Django 3.2.4 on 2021-09-08 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directoryapp', '0009_invitation_private_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationusage',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_uses', to='directoryapp.tenant'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
